version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    volumes:
      - ./themes:/var/www/html/wp-content/themes
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-data:
    driver: local
